/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CountriesCardGrid: typeof import('./components/pages/countries/countries-card-grid.vue')['default']
    CountryCard: typeof import('./components/pages/countries/country-card.vue')['default']
    CountryCardFull: typeof import('./components/pages/countries/country-card-full.vue')['default']
    GeneralInfoSection: typeof import('./components/pages/index/general-info-section.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
